name=k_comp_oled
version=1.0
author=Andreas Kucher
maintainer=Andreas Kucher
sentence=OLED Library and test program
paragraph=bar
category=Display
url=https://github.com/andkuc/k-comp
architectures=avr

