name=k_comp_oled_adafruit
version=1.0
author=Andreas Kucher
maintainer=Andreas Kucher
sentence=Library and test program taken from Adafruit (see headers in the files and license.txt)
paragraph=bar
category=Display
url=https://github.com/andkuc/k-comp
architectures=avr

