name=k_comp_oled_grid
version=1.0
author=Andreas Kucher
maintainer=Andreas Kucher
sentence=OLED Grid Library and test program
paragraph=bar
category=Display
url=https://github.com/andkuc/k-comp
architectures=avr

