name=k_comp_oled_paged
version=1.0
author=Andreas Kucher
maintainer=Andreas Kucher
sentence=Paged OLED Library and test program
paragraph=bar
category=Display
url=https://github.com/andkuc/k-comp
architectures=avr

